### ISSUE TITLE
Progressive-enhancement configuration?

### ISSUE THREAD

**Issue by tigt** [GoogleChromeLabs/file-drop#11]
Would it be possible to configure this element like so:

```html
<file-drop>
  <label>Image file to check:
    <input type="file" accepts="image/*" name="upload" etc...>
  </label>
</file-drop>
```

In my app, I'm concerned about users on REALLY bad connections, so I'd like to offer them something that works if the JS times out, or if they intentionally block it.

**Comment by PaulKinlan** [comment]
you should be able to do this via CSS, try the following.

```
file-drop:defined label {
  display:none;
}
```

When the element is defined and available to use it will hide the label, if not then it will be visible.

**Comment by tigt** [comment]
Right, it just kind of stinks that I have to configure the `<file-drop>` element’s attributes *and* the inner fallback’s, when I thought the Slot API could hoover up the inner `<input>` and use those attributes too.

But maybe I misunderstood the spec.

**Comment by tigt** [comment]
Ah, makes sense. That's too bad, but I understand.

Thanks for your time!

**Comment by PaulKinlan** [comment]
I don;t think Shadow DOM helps in this case. What you are asking for is that I don't re-slot certain child elements when the element is active which I have no way of knowing which should be projected through the WC DOM. The element is a wrapper for the drop-target so it has to re-project everything inside of it.

The use-case you have is valid, and that is exactly what the `:defined` psuedo class is meant to help with. When the JS has not been run because it is being downloaded (or blocked) then the WC is not registered and thus is not active yet.
